on:
  repository_dispatch:
    types: [master_push]

jobs:
  build-and-publish-wasm-windows-electron:
    runs-on: windows-latest
    steps:
      - run: git clone https://github.com/namseent/namseent
